version: 2
multi-ecosystem-groups:
  all-updates:
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependabot"
    commit-message:
      prefix: "chore"

updates:
  - package-ecosystem: "uv"
    directory: "/"
    multi-ecosystem-group: "all-updates"
    patterns:
      - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "all-updates"
    patterns:
      - "*"
